---

:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :test_file_prefix: test_
  :which_ceedling: test/vendor/ceedling
  :default_tasks:
    - test:all

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
    - -:test/vendor/**
  :source:
    - src/**
    - inc/**
    - out/staging/inc/**
  :support:
    - test/support

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:gcov:
    :html_report_type: basic

:libraries:
  :placement: :end
  :flag: "${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
  :release:
    - *common_libraries

:plugins:
  :load_paths:
    - test/vendor/ceedling/plugins
  :enabled:
    - gcov
    - stdout_pretty_tests_report
    - module_generator
    - raw_output_report
    - command_hooks

:tools_test_compiler:
  :executable: gcc
  :arguments:
    - -std=gnu99
    - -ggdb
    - -Wall -Wextra -Werror -Wuninitialized
    - -Wconversion -Wsign-conversion
    - -Wparentheses -Winit-self -Wcomment

:tools_test_linker:
  :arguments:
    - -Lout/staging/lib -Wl,-rpath,out/staging/lib
    - -lexpat

:tools_gcov_linker:
  :arguments:
    - -Lout/staging/lib -Wl,-rpath,out/staging/lib
    - -lexpat

:tools:
  :pre_test_fixture_execute:
    :executable: valgrind
    :arguments:
      - --track-origins=yes
      - --leak-check=full
      - --show-leak-kinds=all
      - --errors-for-leak-kinds=all
      - --error-exitcode=10
      - ${1}

...
